<!DOCTYPE html><html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Dartの非同期処理の理解を深める（Tips編） | Kabolog</title><link rel="canonical" href="https://blog.kaboc.cc/posts/20221220-01gmqz2kpr"><link rel="author" href="http://www.hatena.ne.jp/kabochapo/"><link rel="shortcut icon" href="../favicon.ico"><link rel="icon" type="image/png" href="../res/images/android-chrome-192x192.png"><link rel="apple-touch-icon" href="../res/images/apple-touch-icon.png"><link rel="stylesheet" href="../res/css/styles.css?202305081040"><link rel="preload" href="../res/css/github-markdown-light.css" as="style" onload="this.onload=null;this.rel='stylesheet'"><link rel="preload" href="../res/css/obsidian.min.css" as="style" onload="this.onload=null;this.rel='stylesheet'"><meta name="title" content="Dartの非同期処理の理解を深める（Tips編） | Kabolog"><meta name="description" content="Dart Advent Calendar 2022 の 20 日目の記事です。 一昨日から非同期処理のシリーズとして書いています。 非同期関連のことばかり書いていると飽きるのでシリーズ最終回とします。 18 日目 - Dartの非同期処理の理解を深める（キュー編） 19 日目 - Dartの非同期処理の理解を深める（エラーハンドリング編） 20 日目 - D"><meta name="keywords" content="Dart,非同期処理"><meta name="author" content="kaboc"><meta property="og:type" content="article"><meta property="og:url" content="https://blog.kaboc.cc/posts/20221220-01gmqz2kpr"><meta property="og:image" content="https://blog.kaboc.cc/res/images/og-1200x630.jpg"><meta property="og:site_name" content="Kabolog"><meta property="og:title" content="Dartの非同期処理の理解を深める（Tips編） | Kabolog"><meta property="og:description" content="Dart Advent Calendar 2022 の 20 日目の記事です。 一昨日から非同期処理のシリーズとして書いています。 非同期関連のことばかり書いていると飽きるのでシリーズ最終回とします。 18 日目 - Dartの非同期処理の理解を深める（キュー編） 19 日目 - Dartの非同期処理の理解を深める（エラーハンドリング編） 20 日目 - D"><meta name="twitter:card" content="summary"><meta name="twitter:image" content="https://blog.kaboc.cc/res/images/og-square.jpg"><meta name="twitter:site" content="@kabochapo"><meta name="twitter:creator" content="@kabochapo"><script defer src="../res/js/highlight.min.js"></script><script>window.onload = () => hljs.highlightAll();</script><script async src="https://www.googletagmanager.com/gtag/js?id=G-8T92E4QR06"></script>
<script>
window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-8T92E4QR06');
</script></head><body><div id="blog-view"><header><p><span><a href="../">Kabolog</a></span><span id="top-social-buttons"><a href="https://kaboc.cc/"><img src="../res/images/home.svg" alt="Home" width="20" height="20"></a><a href="https://twitter.com/kabochapo" target="_blank" rel="noopener"><img src="../res/images/brand-twitter.svg" alt="Twitter" width="20" height="20"></a><a href="https://github.com/kaboc" target="_blank" rel="noopener"><img src="../res/images/brand-github.svg" alt="GitHub" width="20" height="20"></a></span></p></header><div id="view-content"><main><h1 id="post-title">Dartの非同期処理の理解を深める（Tips編）</h1><section id="post-meta"><ul id="category-list"><li><a href="../?c=Dart%3A%3A%E9%9D%9E%E5%90%8C%E6%9C%9F%E5%87%A6%E7%90%86">Dart &gt; 非同期処理</a></li></ul><time datetime="2022-12-20T14:30:22.662935Z">2022-12-20</time></section><article class="markdown-body"><p><a href="https://qiita.com/advent-calendar/2022/dart" target="_blank" rel="noopener">Dart Advent Calendar 2022</a> の 20 日目の記事です。</p>
<p>一昨日から非同期処理のシリーズとして書いています。<br>
非同期関連のことばかり書いていると飽きるのでシリーズ最終回とします。</p>
<ul>
<li>18 日目 - <a href="https://blog.kaboc.cc/posts/20221218-01gmj1228q" target="_blank" rel="noopener">Dartの非同期処理の理解を深める（キュー編）</a></li>
<li>19 日目 - <a href="https://blog.kaboc.cc/posts/20221219-01gmnatcf5" target="_blank" rel="noopener">Dartの非同期処理の理解を深める（エラーハンドリング編）</a></li>
<li>20 日目 - Dartの非同期処理の理解を深める（Tips編）</li>
</ul>
<h1 id="%E4%B8%A6%E8%A1%8C%E5%AE%9F%E8%A1%8C">並行実行</h1>
<p>複数の非同期処理を一つずつ順番に実行しなくていい場合、並行させるほうが全部が終わるまでの時間を短縮できます。</p>
<h2 id="Future.wait()">Future.wait()</h2>
<p><a href="https://api.dart.dev/stable/dart-async/Future/wait.html" target="_blank" rel="noopener">wait()</a> を使うと、複数の処理を並行して実行して List の形で結果を得ることができます。<br>
その List は Future になっていて、全部が終わったとき（またはオプション指定によってはエラー時）に解決するので、await して全体の完了を待つことができます。<br>
List 内の結果の順序は渡された非同期関数と同じです。</p>
<p>次の例では 1 ～ 3 の数字が付いた関数が逆順に完了してそれぞれの数が返されますが、結果の List は <code>[1, 2, 3]</code> となります。</p>
<pre><code class="language-dart">Future&lt;int&gt; asynchronousFunc1() {  
  return Future.delayed(const Duration(milliseconds: 30), () =&gt; 1);  
}  
  
Future&lt;int&gt; asynchronousFunc2() {  
  return Future.delayed(const Duration(milliseconds: 20), () =&gt; 2);  
}  
  
Future&lt;int&gt; asynchronousFunc3() {  
  return Future.delayed(const Duration(milliseconds: 10), () =&gt; 3);  
}  
  
Future&lt;void&gt; main() async {  
  final results = await Future.wait([  
    asynchronousFunc1(),  
    asynchronousFunc2(),  
    asynchronousFunc3(),  
  ]);  
  
  print(results); // [1, 2, 3]  
}  
</code></pre>
<h3 id="%E4%B8%80%E3%81%A4%E3%81%AE%E9%96%A2%E6%95%B0%E3%81%A7%E3%82%A8%E3%83%A9%E3%83%BC%E3%81%8C%E8%B5%B7%E3%81%93%E3%81%A3%E3%81%9F%E5%A0%B4%E5%90%88">一つの関数でエラーが起こった場合</h3>
<p><code>asynchronousFunc2()</code> で例外を起こしてみましょう。</p>
<pre><code class="language-dart">Future&lt;int&gt; asynchronousFunc2() async {  
  print('asynchronousFunc2'); // 実行されたことやタイミングを確認しやすくするためのprint  
  throw Exception('Failed at 2');  
}  
</code></pre>
<p>他の二つの関数にも print を追加しておきます（コードは省略）。</p>
<p>エラーが起こるのは三つのうち一つだけですが、<code>wait()</code> 自体でエラーが起こった状態になるのでその部分で対処が必要です。<br>
<code>onError()</code> を用いると、三つのうちどれが失敗したのかわからないことと、その場で main 関数から抜けたくてもできないことから、try-catch のほうがここでは使いやすいと思います。</p>
<p>※<code>onError()</code> については <a href="https://blog.kaboc.cc/posts/20221219-01gmnatcf5" target="_blank" rel="noopener">昨日の記事</a> をご覧ください。</p>
<pre><code class="language-dart">  final List&lt;int&gt; results;  
  
  try {  
    final results = await Future.wait([ ... ]);  
    print(result);  
  } on Exception catch (e) {  
    print(e);  
  }  
</code></pre>
<p>実行すると、追加しておいた print によって下記のように出力されます。<br>
途中でエラーが起こっても全てが実行されるまで Future が解決しない動作になっています。</p>
<pre><code class="language-text">asynchronousFunc3  
asynchronousFunc2  
asynchronousFunc1  
Exception: Failed at 2  
</code></pre>
<h3 id="%E8%A4%87%E6%95%B0%E3%81%AE%E9%96%A2%E6%95%B0%E3%81%A7%E3%82%A8%E3%83%A9%E3%83%BC%E3%81%8C%E8%B5%B7%E3%81%93%E3%81%A3%E3%81%9F%E5%A0%B4%E5%90%88">複数の関数でエラーが起こった場合</h3>
<p>三番目に実行される関数でも throw された場合、<code>wait()</code> のエラーは先に起こった二番目の内容になります。</p>
<h3 id="%E4%B8%80%E3%81%A4%E3%81%8C%E3%82%A8%E3%83%A9%E3%83%BC%E3%81%AB%E3%81%AA%E3%81%A3%E3%81%9F%E3%82%89%E3%81%99%E3%81%90%E3%81%AB%E6%AD%A2%E3%82%81%E3%82%8B">一つがエラーになったらすぐに止める</h3>
<p><code>wait()</code> には <code>eagerError</code> という引数があり、デフォルトは <code>false</code> です。<br>
<code>true</code> を指定すると、エラーが起こったときに <code>wait()</code> の Future が即解決してエラーになります。</p>
<p><code>eagerError</code> の指定を追加して実行してみましょう。</p>
<pre><code class="language-dart">results = await Future.wait(  
  eagerError: true,  
  [ ... ],  
);  
</code></pre>
<pre><code class="language-text">asynchronousFunc3  
asynchronousFunc2  
Exception: Failed at 2  
asynchronousFunc1  
</code></pre>
<p>先ほどと違ってエラーが起きた時点で catch ブロックに至っていることがわかります。<br>
その後に 1 の結果が出力されているのは、例外が発生する前に既に 1 の <code>Future.delayed</code> は実行されていて、そのコールバックは例外が起こっても止まらないからです。</p>
<h3 id="%E3%82%A8%E3%83%A9%E3%83%BC%E3%81%8C%E8%B5%B7%E3%81%93%E3%81%A3%E3%81%A6%E3%82%82%E7%B5%90%E6%9E%9C%E3%82%92%E5%80%8B%E5%88%A5%E3%81%AB%E7%A2%BA%E8%AA%8D%E3%81%97%E3%81%9F%E3%81%84">エラーが起こっても結果を個別に確認したい</h3>
<p>上の方法では Future がエラーとして解決され、個々の関数の結果は results に入りません。<br>
並行実行しつつ個々の結果を得る方法の一つに <code>package:async</code> の <a href="https://pub.dev/documentation/async/latest/async/Result-class.html" target="_blank" rel="noopener">Result</a> クラスがあります。</p>
<pre><code class="language-dart">import 'package:async/async.dart';  
  
Future&lt;Result&lt;int&gt;&gt; asynchronousFunc1() {  
  return Future.delayed(const Duration(milliseconds: 30), () =&gt; Result.value(1));  
}  
  
Future&lt;Result&lt;int&gt;&gt; asynchronousFunc2() {  
  return Future.delayed(const Duration(milliseconds: 20), () =&gt; Result.error(Exception('Failed at 2')));  
}  
  
Future&lt;Result&lt;int&gt;&gt; asynchronousFunc3() {  
  return Future.delayed(const Duration(milliseconds: 10), () =&gt; Result.value(3));  
}  
...  
  
Future&lt;void&gt; main() async {  
  final results = await Future.wait([  
    asynchronousFunc1(),  
    asynchronousFunc2(),  
    asynchronousFunc3(),  
  ]);  
  
  for (var i = 0; i &lt; results.length; i++) {  
    final r = results[i];  
    print('[$i] ${r.isError ? r.asError!.error : r.asValue!.value}');  
  }  
}  
</code></pre>
<p>1 と 3 では <code>Result.value</code>（<code>ValueResult</code> 型）、2 だけは <code>Result.error</code>（<code>ErrorResult</code> 型）を返しています。<br>
型の確認は <code>isValue</code> と <code>isError</code>（または <code>is</code> 演算子）、値やエラーを取り出すのはそれぞれ <code>asValue!.value</code>、<code>asError!.error</code> でできます。</p>
<p>実行すると次のようになります。</p>
<pre><code class="language-text">asynchronousFunc3  
asynchronousFunc2  
asynchronousFunc1  
[0] 1  
[1] Exception: Failed at 2  
[2] 3  
</code></pre>
<p>エラーの捕捉は <code>wait()</code> の実行時ではなく <code>wait()</code> によって実行される非同期関数側で行い、エラーであれば <code>return Result.error(...);</code> を行うという形になります。</p>
<h2 id="FutureGroup">FutureGroup</h2>
<p><code>Future.wait()</code> の他に package:async の <a href="https://pub.dev/documentation/async/latest/async/FutureGroup-class.html" target="_blank" rel="noopener">FutureGroup</a> も使えます。</p>
<p>主な違いは、実行する Future を一度に指定せずに <code>add()</code> で追加していける点です。<br>
エラー時の動作は <code>Future.wait()</code> で <code>eagerError</code> を有効にしたときと同様です。</p>
<p>同じ例を書き換えたものを載せますので参考にしてください。</p>
<pre><code class="language-dart">Future&lt;void&gt; main() async {  
  final group = FutureGroup&lt;int&gt;()  
    ..add(asynchronousFunc1())  
    ..add(asynchronousFunc2())  
    ..add(asynchronousFunc3())  
    ..close();  
  
  try {  
    final results = await group.future;  
    print(results);  
  } on Exception catch (e) {  
    print(e);  
  }  
}  
</code></pre>
<pre><code class="language-text">asynchronousFunc3  
asynchronousFunc2  
Exception: Failed at 2  
asynchronousFunc1  
</code></pre>
<h1 id="%E3%82%AD%E3%83%A3%E3%83%B3%E3%82%BB%E3%83%AB%E3%81%99%E3%82%8B">キャンセルする</h1>
<p>package:async の <a href="https://pub.dev/documentation/async/latest/async/CancelableOperation-class.html" target="_blank" rel="noopener">CancelableOperation</a> でできます。<br>
以前に書いた記事が Qiita にあるので、気になる方はそちらをお読みください。</p>
<ul>
<li><a href="https://qiita.com/kabochapo/items/c5061240f90468d16527" target="_blank" rel="noopener">DartでFutureをキャンセルする - Qiita</a></li>
</ul>
<p><code>CancelableOperation</code> の Completer である <a href="https://pub.dev/documentation/async/latest/async/CancelableCompleter/CancelableCompleter.html" target="_blank" rel="noopener">CancelableCompleter</a> もあり、必要になったときに思い出せるように存在だけでも覚えておくと良いと思います。</p>
<h1 id="%E3%82%84%E3%82%8A%E7%9B%B4%E3%81%9B%E3%82%8B%20Timer">やり直せる Timer</h1>
<p>package:async の <a href="https://pub.dev/documentation/async/latest/async/RestartableTimer-class.html" target="_blank" rel="noopener">RestartableTimer</a> を使うとタイマーを再実行できます。<br>
これは dart:async の <a href="https://api.dart.dev/stable/dart-async/Timer-class.html" target="_blank" rel="noopener">Timer</a> を実装したもので、違いは主に次の二点だけです。</p>
<ul>
<li>定期実行のための名前付きの <code>.periodic</code> コンストラクタがない</li>
<li><a href="https://pub.dev/documentation/async/latest/async/RestartableTimer/reset.html" target="_blank" rel="noopener">reset()</a> というメソッドがある</li>
</ul>
<h2 id="reset()">reset()</h2>
<p>メソッド名から「開始位置を戻す」のみの動作に思えますが「戻す＋タイマー開始」です。<br>
これより前に中断または終了していてもそこからの再開ではなく最初からになります。<br>
restart ではなく reset という語が使われているのはそれを明確にするためだろうと思います。</p>
<p>既に動いているときに最初に戻したい場合に先に <code>cancel()</code> せずに使えます。</p>
<pre><code class="language-dart">import 'package:async/async.dart';  
  
Future&lt;void&gt; main() async {  
  final stopwatch = Stopwatch();  
  
  // 3秒後にコールバック関数を実行するタイマー（生成と同時に動き出す）  
  final timer = RestartableTimer(Duration(seconds: 3), () {  
    // 3秒経過時に呼ばれて秒数が表示される  
    final elapsedSeconds = (stopwatch.elapsedMilliseconds / 1000).round();  
    print(elapsedSeconds); // 3  
  });  
  
  // 2秒後に時間計測を開始＆タイマーを始めに戻して実行  
  await Future&lt;void&gt;.delayed(const Duration(seconds: 2));  
  stopwatch.start();  
  timer.reset();  
}  
</code></pre>
<h1 id="%E9%9D%9E%E5%90%8C%E6%9C%9F%E5%87%A6%E7%90%86%E3%81%AE%E7%B5%90%E6%9E%9C%E3%82%92%E3%82%AD%E3%83%A3%E3%83%83%E3%82%B7%E3%83%A5%E3%81%99%E3%82%8B">非同期処理の結果をキャッシュする</h1>
<p>キャッシュの機能を持つ状態管理パッケージもありますが、付属していなくても可能です。</p>
<h2 id="AsyncMemoizer">AsyncMemoizer</h2>
<p>またまた package:async です。<br>
<a href="https://pub.dev/documentation/async/latest/async/AsyncMemoizer-class.html" target="_blank" rel="noopener">AsyncMemoizer</a> でキャッシュ（メモ化）することができます。</p>
<pre><code class="language-dart">import 'dart:async';  
import 'package:async/async.dart';  
  
void main() {  
  final memoizer = AsyncMemoizer&lt;int&gt;();  
  
  Timer.periodic(const Duration(seconds: 1), (timer) async {  
    final tick = timer.tick;  
    final v = await memoizer.runOnce(() =&gt; tenfoldOf(tick));  
    print('[$tick] $v');  
  
    if (tick == 5) timer.cancel();  
  });  
}  
  
Future&lt;int&gt; tenfoldOf(int tick) async {  
  print('Called at tick $tick');  
  return tick * 10;  
}  
</code></pre>
<pre><code class="language-text">Called at tick 1  
[1] 10  
[2] 10  
[3] 10  
[4] 10  
[5] 10  
</code></pre>
<h3 id="runOnce()">runOnce()</h3>
<p>上の例では、10 倍の数を返す <code>tenfoldOf()</code> が <a href="https://pub.dev/documentation/async/latest/async/AsyncMemoizer/runOnce.html" target="_blank" rel="noopener">runOnce()</a> のコールバックから呼ばれます。<br>
<code>runOnce()</code> は定期実行のタイマーで 5 回呼ばれるのにコールバックは最初しか実行されない様子がこの例で見えます。</p>
<h3 id="hasRun">hasRun</h3>
<p>ここでは使いませんでしたが、<code>runOnce()</code> が既に呼ばれたかどうかを <a href="https://pub.dev/documentation/async/latest/async/AsyncMemoizer/hasRun.html" target="_blank" rel="noopener">hasRun</a> というプロパティの値を見て確認できます。</p>
<h2 id="AsyncCache">AsyncCache</h2>
<p>package:async の <a href="https://pub.dev/documentation/async/latest/async/AsyncCache-class.html" target="_blank" rel="noopener">AsyncCache</a> で <code>AsyncMemoizer</code> より柔軟にキャッシュを扱えます。</p>
<p>キャッシュする期間の指定と必要に応じたクリアが可能で、変化の頻度が低いデータを何度も取得しないようにしたりコストの高い処理の実行を間引いたりするのに役立ちます。</p>
<pre><code class="language-dart">void main() {  
  final cache = AsyncCache&lt;int&gt;(const Duration(seconds: 3));  
  
  Timer.periodic(const Duration(seconds: 1), (timer) async {  
    final tick = timer.tick;  
    final v = await cache.fetch(() =&gt; tenfoldOf(tick));  
    print('[$tick] $v');  
  
    if (tick == 6) cache.invalidate();  
    if (tick == 8) timer.cancel();  
  });  
}  
</code></pre>
<pre><code class="language-text">Called at tick 1  
[1] 10  
[2] 10  
[3] 10  
[4] 10  
Called at tick 5  
[5] 50  
[6] 50  
Called at tick 7  
[7] 70  
[8] 70  
</code></pre>
<h3 id="fetch()">fetch()</h3>
<p><code>tenfoldOf()</code> が <a href="https://pub.dev/documentation/async/latest/async/AsyncCache/fetch.html" target="_blank" rel="noopener">fetch()</a> のコールバックから呼ばれるようになっています。<br>
<code>fetch()</code> は毎秒実行されますが、キャッシュの期間として設定している 3 秒間はコールバックがスキップされてキャッシュ済みのデータが返されます。</p>
<p>※出力結果で 4 秒置きになっているのは、1 秒目が実行されてから 2 ～ 4 秒目の 3 秒間にキャッシュデータが使われるからです。</p>
<h3 id="invalidate()">invalidate()</h3>
<p><a href="https://pub.dev/documentation/async/latest/async/AsyncCache/invalidate.html" target="_blank" rel="noopener">invalidate()</a> でキャッシュをクリアできます。<br>
上の例では 6 秒経ったときに実行しているので 7 秒目で <code>tenFoldOf()</code> が再実行されています。</p>
<h1 id="await%20%E3%81%97%E3%81%AA%E3%81%84">await しない</h1>
<p><a href="https://dart-lang.github.io/linter/lints/unawaited_futures.html" target="_blank" rel="noopener">unawaited_futures</a> の lint ルールを有効にすると、Future の解決を待つことを忘れているときに警告してくれます。<br>
しかし待たなくてもいい非同期処理もあります。</p>
<h2 id="unawaited()">unawaited()</h2>
<p><a href="https://api.dart.dev/stable/dart-async/unawaited.html" target="_blank" rel="noopener">unawaited()</a> はまさにその用途で Dart 2.14 ～ 2.15 にて追加された関数です。<br>
（変更履歴によれば 2.14 ですが、ソースコード上で <code>@Since("2.15")</code> になっています。）</p>
<pre><code class="language-dart">import 'dart:async';  
  
Future&lt;void&gt; main() async {  
  unawaited(asynchronousFunc());  
}  
</code></pre>
<p>ただし、その非同期処理でエラーが起こると unhandled error になってしまいます。<br>
await していないので try-catch で捕捉することができませんし、<code>unawaited()</code> の戻り値は void なので <code>catchError()</code> や <code>onError()</code> も使えません。<br>
これを利用するのはエラーが起こり得ない場合だけにしましょう。</p>
<p>なお、この関数を使わずに <code>// ignore: unawaited_futures</code> というコメントによって警告を抑え込むこともできますが、意図通りの名前を持つ <code>unawaited()</code> を使うほうがより明確にその意図を伝えることができます。<br>
（コメントでも unawaited ほど明確でないにしても意図は示せるのでお好みで。）</p>
<h2 id="ignore()">ignore()</h2>
<p><a href="https://api.dart.dev/stable/dart-async/FutureExtensions/ignore.html" target="_blank" rel="noopener">FutureExtensions</a> の <a href="https://api.dart.dev/stable/dart-async/FutureExtensions/ignore.html" target="_blank" rel="noopener">ignore()</a> なら待たずに処理結果もエラーも完全に無視できます。<br>
Dart 2.14 で追加されました。</p>
<p>便利ですが、重大なエラーを無視してしまうことがないようにご注意ください。</p>
<pre><code class="language-dart">Future&lt;void&gt; main() async {  
  asynchronousFunc().ignore();  
}  
</code></pre>
<h1 id="%E3%83%86%E3%82%B9%E3%83%88">テスト</h1>
<p>時間経過した状態や未来の日時での動作をテストしたいことがあります。<br>
そんなときに使える便利な方法を見ていきましょう。</p>
<h2 id="FakeAsync">FakeAsync</h2>
<p>例として、30 秒経つと値が消えるクラスを使います。<br>
経過するまでは既にある値のままというキャッシュ機能です。</p>
<p>一定期間だけのキャッシュといえば <a href="#AsyncCache">AsyncCache</a> ですが、使いにくかったのでタイマーにしました。<br>
そのことは後述します。</p>
<pre><code class="language-dart">class ValueCache&lt;T&gt; {  
  ValueCache(T? value) {  
    updateValue(value);  
  }  
  
  T? _value;  
  Timer? _timer;  
  
  T? get value =&gt; _value;  
  
  void updateValue(T? value) {  
    _timer?.cancel();  
    if (value != null) {  
      _timer = Timer(const Duration(seconds: 30), () =&gt; _value = null);  
    }  
  
    _value = value;  
  }  
}  
</code></pre>
<p>時間の長さを渡して変更できるようになっていないので、何も考慮せずにテストすると 30 秒間も待たなければなりません。</p>
<pre><code class="language-dart">test('...', () async {  
  final cache = ValueCache(123);  
  expect(cache.value, equals(123));  
  
  await Future&lt;void&gt;.delayed(const Duration(seconds: 30)); // ここで待たされる  
  expect(cache.value, isNull);  
});  
</code></pre>
<p>そこで役立つのが  <a href="https://pub.dev/packages/fake_async" target="_blank" rel="noopener">fake_async</a> です。<br>
<a href="https://pub.dev/documentation/fake_async/latest/fake_async/fakeAsync.html" target="_blank" rel="noopener">fakeAsync()</a> を使い、コールバックで <a href="https://pub.dev/documentation/fake_async/latest/fake_async/FakeAsync-class.html" target="_blank" rel="noopener">FakeAsync</a> のインスタンスを用いて <a href="https://pub.dev/documentation/fake_async/latest/fake_async/FakeAsync/elapse.html" target="_blank" rel="noopener">elapse()</a> で時間を先送りでき、下記テストは 30 秒間待たずに短時間で終わります。</p>
<pre><code class="language-dart">import 'package:fake_async/fake_async.dart';  
  
...  
  
test('...', () {  
  fakeAsync((async) {  
    final cache = ValueCache(123);  
    expect(cache.value, equals(123));  
      
    async.elapse(const Duration(seconds: 30)); // 30秒経ったことにする  
    expect(cache.value, isNull);  
  });  
</code></pre>
<p>ただ残念なことに、<code>await</code> が使えなくなります。<br>
この例では await する必要がないようにしたので簡潔に書けましたが、Future の結果を使わないといけない場合には <code>then()</code> で外側の変数に値を入れる等の工夫が必要になると思います。</p>
<pre><code class="language-dart">int? value;  
timeConsumingFunc().then((v) =&gt; value = v);  
  
async.elapse(...);  
expect(value, ...);  
</code></pre>
<h3 id="%E6%B3%A8%E6%84%8F">注意</h3>
<p>時間が経ったことにするだけなので、短時間でできない処理（重い処理、通信等で時間がかかる処理など）を待たずに済むようになるわけではありません。</p>
<h3 id="FakeAsync%20%E3%81%AE%E9%9B%A3%E7%82%B9">FakeAsync の難点</h3>
<p>使いにくい点が多くて残念です<br>
関連する issue ページは <a href="https://github.com/dart-lang/fake_async/issues/24" target="_blank" rel="noopener">こちら</a> です。</p>
<h4 id="%E9%9B%A3%E7%82%B9%201">難点 1</h4>
<p>次のようにすると <code>expect()</code> の matcher が何であれ常に成功扱いになってしまいます。<br>
await を使うことではなく <code>fakeAsync()</code> のコールバックを async にすることで起こるようです。</p>
<pre><code class="language-dart">test('...', () {  
  fakeAsync((async) async {  
    final result = await timeConsumingFunc();  
    expect(result, equals('でたらめな値'));  
  });  
});  
</code></pre>
<h4 id="%E9%9B%A3%E7%82%B9%202">難点 2</h4>
<p><code>completion()</code> も使えないようです。<br>
使うとテストが終わらなくなりました。</p>
<p>※使えるときもありましたが理由がわかりませんでした。</p>
<pre><code class="language-dart">test('...', () {  
  fakeAsync((async) {  
    expect(timeConsumingFunc(), completion('expected value'));  
  });  
});  
</code></pre>
<h4 id="%E9%9B%A3%E7%82%B9%203">難点 3</h4>
<p><code>fakeAsync()</code> を await した場合もテストが終わらなくなります。</p>
<pre><code class="language-dart">test('...', () async {  
  final result = await fakeAsync((_) =&gt; timeConsumingFunc());  
  expect(result, equals('expected value'));  
});  
</code></pre>
<h4 id="%E9%9B%A3%E7%82%B9%204">難点 4</h4>
<p>単純に言って「使いにくい」です。<br>
Future の解決を await 以外の方法で何度も待たないといけません。</p>
<p>例えば、ValueCache の AsyncCache 利用版では次のようにテストが長ったらしくなります。</p>
<pre><code class="language-dart">class AsyncValueCache&lt;T&gt; {  
  AsyncValueCache(T? value) {  
    updateValue(value);  
  }  
  
  final _cache = AsyncCache&lt;T?&gt;(const Duration(seconds: 30));  
  
  Future&lt;T?&gt; get value =&gt; _cache.fetch(Future.value);  
  
  void updateValue(T? value) {  
    _cache.fetch(() =&gt; Future.value(value));  
  }  
}  
</code></pre>
<pre><code class="language-dart">fakeAsync((async) {  
  int? value;  
  
  final cache = AsyncValueCache(123);  
  cache.value.then((v) =&gt; value = v);  
  
  // cache.valueはFutureなので解決待ちが必要  
  async.flushMicrotasks();  
  expect(value, equals(123));  
  
  async.elapse(const Duration(seconds: 30));  
  cache.value.then((v) =&gt; value = v);  
  
  // ここでまた解決待ちが必要  
  async.flushMicrotasks();  
  expect(value, isNull);  
});  
</code></pre>
<p><a href="https://pub.dev/documentation/fake_async/latest/fake_async/FakeAsync/flushMicrotasks.html" target="_blank" rel="noopener">flushMicrotasks()</a> は終わっていない microtask を全部次々と実行して消化するメソッドです。<br>
<code>AsyncValueCache</code> では <code>Future.value</code> を使っていて microtask queue に入るのでこのメソッドでできますが、event queue に入っている処理はおそらくこれでは消化されないのでご注意ください。</p>
<p>※類似のメソッドとして <a href="https://pub.dev/documentation/fake_async/latest/fake_async/FakeAsync/flushTimers.html" target="_blank" rel="noopener">flushTimers</a> もあります。<br>
※microtask については一昨日の「<a href="https://blog.kaboc.cc/posts/20221218-01gmj1228q" target="_blank" rel="noopener">Dartの非同期処理の理解を深める（キュー編）</a>」をご覧ください。</p>
<h2 id="Clock">Clock</h2>
<p>FakeAsync で時間を操作しても <code>DateTime</code> の日時や <code>Stopwatch</code> には影響しません。</p>
<pre><code class="language-dart">fakeAsync((async) {  
  final stopwatch = Stopwatch()..start();  
  print(DateTime.now()); // 2022-12-20 22:44:42.339323  
  
  async.elapse(Duration(hours: 3));  
  
  print(stopwatch.elapsedMilliseconds); // 4  
  print(DateTime.now()); // 2022-12-20 22:44:42.344323  
});  
</code></pre>
<p>影響させて FakeAsync による時間操作を活用したテストをしたければ <a href="https://pub.dev/packages/clock" target="_blank" rel="noopener">clock</a> が使えます。<br>
<code>DateTime.now</code>、<code>Stopwatch</code> に対応するものはそれぞれ <a href="https://pub.dev/documentation/clock/latest/clock/Clock/now.html" target="_blank" rel="noopener">clock.now</a>、<a href="https://pub.dev/documentation/clock/latest/clock/Clock/stopwatch.html" target="_blank" rel="noopener">clock.stopwatch</a> です。</p>
<pre><code class="language-dart">import 'package:clock/clock.dart';  
  
...  
  
fakeAsync((async) {  
  final stopwatch = clock.stopwatch()..start();  
  print(clock.now()); // 2022-12-20 22:44:42.349334  
  
  async.elapse(Duration(hours: 3));  
  
  print(stopwatch.elapsedMilliseconds); // 10800000  
  print(clock.now()); // 2022-12-21 01:44:42.349334  
});  
</code></pre>
<p>Clock をアプリなどのコードで使っておけば日時関連のテストがしやすくなります。<br>
<a href="https://pub.dev/documentation/clock/latest/clock/Clock-class.html" target="_blank" rel="noopener">Clock クラス</a> には <code>days.ago()</code>、<code>daysFromNow()</code> などのメソッドもあって、現在を基準とした時間の隔たりを指定することで過去/未来の日時を取得できます。</p>
<h3 id="%E6%97%A5%E6%99%82%E3%82%92%E5%A4%89%E3%81%88%E3%82%8B%E4%BE%BF%E5%88%A9%E3%81%AA%E6%96%B9%E6%B3%95">日時を変える便利な方法</h3>
<h4 id="%E5%88%9D%E6%9C%9F%E5%80%A4%E3%82%92%E8%A8%AD%E5%AE%9A">初期値を設定</h4>
<p><code>fakeAsync()</code> の <code>initialTime</code> で初期値を設定できます。</p>
<pre><code class="language-dart">fakeAsync(  
  initialTime: DateTime(2022, 2, 22),  
  (async) {  
    print(clock.now()); // 2022-02-22 00:00:00.000  
    async.elapse(Duration(hours: 22));  
    print(clock.now()); // 2022-02-22 22:00:00.000  
  },  
);  
</code></pre>
<h4 id="%E6%97%A5%E6%99%82%E3%82%92%E5%9B%BA%E5%AE%9A">日時を固定</h4>
<p>Clock を名前付きの <a href="https://pub.dev/documentation/clock/latest/clock/Clock/Clock.fixed.html" target="_blank" rel="noopener">.fixed</a> コンストラクタで作ると日時を不変にすることができます。</p>
<pre><code class="language-dart">fakeAsync((async) {  
  final clock = Clock.fixed(DateTime(2022, 2, 22));  
  print(clock.now()); // 2022-02-22 00:00:00.000  
  async.elapse(Duration(hours: 22));  
  print(clock.now()); // 2022-02-22 00:00:00.000  
});  
</code></pre>
<h2 id="Flutter%20%E3%81%AE%20testWidgets()">Flutter の testWidgets()</h2>
<p><a href="https://api.flutter.dev/flutter/flutter_test/testWidgets.html" target="_blank" rel="noopener">testWidgets()</a> のコールバックでは実は自動的に <code>FakeAsync</code> が利用されます。<br>
Dart の <code>test()</code> のときのように <code>fakeAsync()</code> を自分で使う必要はなくて、時間を経過させるのは <a href="https://api.flutter.dev/flutter/flutter_test/WidgetTester/pump.html" target="_blank" rel="noopener">pump()</a> でできます。</p>
<pre><code class="language-dart">void main() {  
  testWidgets('Counter increments smoke test', (tester) async {  
    final cache = ValueCache(123);  
    expect(cache.value, equals(123));  
  
    await tester.pump(const Duration(seconds: 30));  
    expect(cache.value, isNull);  
  });  
}  
</code></pre>
<p>これで実際に待たなくても 30 秒が経過したことになって短時間でテストが通ります。<br>
Clock も使えます。</p>
<p>なお（深掘りしていないので理由は把握していませんが）<code>testWidgets()</code> では <code>await</code> や <code>completion()</code> が使えます。</p>
<h3 id="testWidgets()%20%E3%81%AE%E4%B8%AD%E8%BA%AB">testWidgets() の中身</h3>
<p>ここからは詳細を書いているだけなので折りたたんでおきます。<br>
コードはかなり簡略化して掲載します。</p>
<details>  
<summary>クリックで開く</summary>
<p><a href="https://api.flutter.dev/flutter/flutter_test/testWidgets.html" target="_blank" rel="noopener">testWidgets()</a> では <code>TestWidgetsFlutterBinding</code> の <code>runTest()</code> が使われています。<br>
⇒ <a href="https://github.com/flutter/flutter/blob/9fb1ae839e0a47bd7bb5e2a3c6dd594fa6b0764c/packages/flutter_test/lib/src/widget_tester.dart#L126-L187" target="_blank" rel="noopener">ソースコード</a></p>
<pre><code class="language-dart">final binding = TestWidgetsFlutterBinding.ensureInitialized();  
  
test(  
  '...',  
  () =&gt; binding.runTest(() async { ... }, ...),  
  ...,  
});  
</code></pre>
</details>
<h3 id="runTest()%20%E3%81%AE%E4%B8%AD%E8%BA%AB">runTest() の中身</h3>
<details>  
<summary>クリックで開く</summary>
<p><a href="https://api.flutter.dev/flutter/flutter_test/TestWidgetsFlutterBinding/runTest.html" target="_blank" rel="noopener">runTest() のドキュメント</a> より：</p>
<blockquote>
<p>Call the testBody inside a <code>FakeAsync</code> scope on which <code>pump</code> can advance time.</p>
<p>意訳： testBody を <code>FakeAsync</code> のスコープの中で呼びます。そのスコープでは <code>pump</code> で時間を進めることができます。</p>
</blockquote>
<p>中身を覗いてみると実際に FakeAsync や Clock の記述があります。<br>
⇒ <a href="https://github.com/flutter/flutter/blob/9fb1ae839e0a47bd7bb5e2a3c6dd594fa6b0764c/packages/flutter_test/lib/src/binding.dart#L1375-L1422" target="_blank" rel="noopener">ソースコード</a></p>
<pre><code class="language-dart">final fakeAsync = FakeAsync();  
_clock = fakeAsync.getClock(DateTime.utc(2015));  
late Future&lt;void&gt; testBodyResult;  
fakeAsync.run((FakeAsync localFakeAsync) {  
  testBodyResult = _runTest(testBody, ...);  
});  
  
return Future&lt;void&gt;.microtask(() async {  
  final resultFuture = testBodyResult.then((_) { /* 何もしない */ });  
  fakeAsync.flushMicrotasks();  
  return resultFuture;  
});  
</code></pre>
</details>
<h3 id="pump()%20%E3%81%AE%E4%B8%AD%E8%BA%AB">pump() の中身</h3>
<details>  
<summary>クリックで開く</summary>
<p><code>elapse()</code> が使われています。<br>
⇒ <a href="https://github.com/flutter/flutter/blob/9fb1ae839e0a47bd7bb5e2a3c6dd594fa6b0764c/packages/flutter_test/lib/src/binding.dart#L1169-L1190" target="_blank" rel="noopener">ソースコード</a></p>
<pre><code class="language-dart">return TestAsyncUtils.guard&lt;void&gt;(() {  
  if (duration != null) {  
    _currentFakeAsync!.elapse(duration);  
  }  
  ...  
  _currentFakeAsync!.flushMicrotasks();  
  return Future&lt;void&gt;.value();  
});  
</code></pre>
</details>
<h3 id="pumpAndSettle()%20%E3%81%AE%E4%B8%AD%E8%BA%AB">pumpAndSettle() の中身</h3>
<details>  
<summary>クリックで開く</summary>
<p><a href="https://api.flutter.dev/flutter/flutter_test/WidgetTester/pumpAndSettle.html" target="_blank" rel="noopener">pumpAndSettle() のドキュメント</a> より：</p>
<blockquote>
<p>Repeatedly calls <code>pump</code> with the given duration until there are no longer any frames scheduled.</p>
<p>意訳： 予定されているフレームが一切なくなるまで与えられた duration で <code>pump</code> を繰り返し呼びます。</p>
</blockquote>
<p>⇒ <a href="https://github.com/flutter/flutter/blob/9fb1ae839e0a47bd7bb5e2a3c6dd594fa6b0764c/packages/flutter_test/lib/src/widget_tester.dart#L661-L696" target="_blank" rel="noopener">ソースコード</a></p>
<pre><code class="language-dart">return TestAsyncUtils.guard&lt;int&gt;(() async {  
  final DateTime endTime = binding.clock.fromNowBy(timeout);  
  int count = 0;  
  do {  
    ...  
    await binding.pump(duration, phase);  
    count += 1;  
  } while (binding.hasScheduledFrame);  
  return count;  
});  
</code></pre>
</details>
</article><section id="bottom-social-buttons"><a href="https://twitter.com/share?url=https%3A%2F%2Fblog.kaboc.cc%2Fposts%2F20221220-01gmqz2kpr&amp;text=Dart%E3%81%AE%E9%9D%9E%E5%90%8C%E6%9C%9F%E5%87%A6%E7%90%86%E3%81%AE%E7%90%86%E8%A7%A3%E3%82%92%E6%B7%B1%E3%82%81%E3%82%8B%EF%BC%88Tips%E7%B7%A8%EF%BC%89%20%7C%20Kabolog&amp;via=kabochapo" title="ツイートする" target="_blank" rel="noopener"><img src="../res/images/twitter-button.svg" alt="ツイートする" width="40" height="40"></a><a href="https://b.hatena.ne.jp/entry/" class="hatena-bookmark-button" data-hatena-bookmark-layout="touch" title="このエントリーをはてなブックマークに追加"><img src="https://b.st-hatena.com/images/v4/public/entry-button/button-only@2x.png" alt="このエントリーをはてなブックマークに追加" width="40" height="40" style="border: none;"></a><script async src="https://b.st-hatena.com/js/bookmark_button.js" charset="utf-8"></script></section></main></div><footer><p><a href="../">Kabolog</a></p><small>&copy; 2022 <a href="https://kaboc.cc/">kaboc</a></small></footer></div></body></html>